### ISSUE TITLE
something may got wrong

### ISSUE THREAD

**Issue by chengrs** [miltonneal54/GerberVS#2]
Hi

I recently start to trace your code and I found something strange.

see blow
![image](https://user-images.githubusercontent.com/1435986/112570505-1e660700-8e21-11eb-8fca-c7c910eda07d.png)

                            case 'N':
                                gerberImage.Format.SequenceNumberLimit = nextCharacter - '0';
                                break;

it should be something like this

                            case 'N':
                                gerberImage.Format.SequenceNumberLimit = lineReader.Read() - '0';
                                break;

but I don't have any gerber file that can test this, my recommend is simply based on the spec

anyway, your code is elegant, thanks for your contribution~~

**Comment by miltonneal54** [comment]
Hi chengrs
Thanks for picking this up and letting me know. The reason that this has not presented any issues to date is the the 4 parameters Nn, Gn, Dn and Mn have been depreciated for some years now and been removed from the specification. Even if you had a very old gerber file, these parameters may not have been used. But all the same I've fixed the issue and will update Github soon.
Thanks again Milton
