### ISSUE TITLE
Read Integer from File not correct

### ISSUE THREAD

**Issue by xiejiahe** [miltonneal54/GerberVS#3]
if load a file with integer with or without character "+" or "-" the total number length is wrong, results in the integer number is also not correct. The Function GetIntegerValue with correction as bellow:

length++;

instead of 

                if ((nextCharacter == '-' && isFirst) || (nextCharacter == '+' && isFirst))
                {                    
                    // if "+" or "-" charater is not inculing in number portion, Length DO NOT +1
                }
                else
                {
                    length++;
                }

**Comment by miltonneal54** [comment]
Thanks for spotting this. I'll fix the code and update the repository.
Milton

**Comment by miltonneal54** [comment]
Issue fixed.
