### ISSUE TITLE
lack something dll. 

### ISSUE THREAD

**Issue by RedDustBoy** [miltonneal54/GerberVS#4]
such as CustomCommonDialog、Rule、FileListbox

**Comment by miltonneal54** [comment]
Your are correct. For some reason the references to these custom controls got lost.
I will be uploading an updated version soon and will correct this.
Thanks for bring this issue to my attention. Milton

**Comment by miltonneal54** [comment]
I've uploaded an updated project. Should have all the correct references to the custom controls. Please note that I have updated the project to VS2017. Let me know if all is ok and I'll close the issue. Milton
