### ISSUE TITLE
About Commercial Use

### ISSUE THREAD

**Issue by elautoweiyi** [miltonneal54/GerberVS#5]
Hi,
I am a new programmer from Taiwan.
I'm preparing a program for our company.
you
Can I refer to or use your code and.dll
And for commercial use?

I apologize in advance if this question offends you.

**Comment by miltonneal54** [comment]
The GerberVS library is free to use as long a you abide by the conditions set out in the licence notice. This notice is at the beginning of all the library source file.
Thank you Milton

**Comment by elautoweiyi** [comment]
I appreciate you taking the time to tell me.
