### ISSUE TITLE
Got problem when compiling

### ISSUE THREAD

**Issue by ofwaetne** [miltonneal54/GerberVS#6]
Hi there , 
I try to compile in visual studio and got some problem
in  function TranslateImage()
it got System.NullReferenceException  in renderinfo.DisplayWidth = pcbImagePanel.Width / displayDpiX; Line
Can I know how to fix it? 

Great thanks for the hardwork

**Comment by miltonneal54** [comment]
Hello,
Firstly, I assume that the project compiles ok. System.NullReferenceException is a .Net runtime exception.
Do you know what object is giving the System.NullReferenceException, is it renderInfo or pcbImagePanel. Both of these are intialised in the Form initialise and Form Load so should not be null values. You can but a break point at the first line of the TranslateImage() method and check the values of renderInfo and the pcbImagePanel.
What version of VS are you using? Have you modified any of the original code?
The code compiles and runs correctly for me.
Thanks Milton

**Comment by ofwaetne** [comment]
Dear Milton
Hi , really thanks for your reply
I have fix the problem by initailize the renderinfo when setting the values
I'm using VS2019 
Great thanks

**Comment by miltonneal54** [comment]
Ok, I will close the issue.
Milton

**Comment by forthyen** [comment]
> Dear Milton Hi , really thanks for your reply I have fix the problem by initailize the renderinfo when setting the values I'm using VS2019 Great thanks

Could you post your modified code ?

**Comment by fanncyyu** [comment]
Pls post your modified code.I also have the same problem.Thank you.
