### ISSUE TITLE
It is recommended to extend the functions of rotating layers and mirroring layers

### ISSUE THREAD

**Issue by JIANHUA1234** [miltonneal54/GerberVS#7]
I extended the rotation layer, and the mirror layer, but the graphics selection cannot be selected correctly after rotation, please help
thanks

**Comment by miltonneal54** [comment]
Layer rotation was never a valid Gerber command. At least to the best of my knowlege. I found no reference to layer rotation in any of the gerber specifications. Therefore I never supported it.
Gerbv supports "RO" (rotate layer) command, but also states that it is not found in any Gerber specifications.
Regards Milton

**Comment by JIANHUA1234** [comment]
Thank you, and is it possible to support mouse-centered zooming like Gerbv, I tried this many times but the result is not ideal

**Comment by JIANHUA1234** [comment]
Ok, thank you, can you support zooming in the center of the mouse like Gerbv? I have tried many times, but the effect is not ideal. These commands are all useful to me. Can you guide me?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miltonneal54/GerberVS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月4日(星期六) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [miltonneal54/GerberVS] It is recommended to extend the functions of rotating layers and mirroring layers (Issue #7)





 
Layer rotation was never a valid Gerber command. At least to the best of my knowlege. I found no reference to layer rotation in any of the gerber specifications. Therefore I never supported it.
 Gerbv supports "RO" (rotate layer) command, but also states that it is not found in any Gerber specifications.
 Regards Milton

**Comment by miltonneal54** [comment]
Currently working on that feature. Still having a few issues, but will update when I get it working, along with a few other updates I've been working on.
Milton
